name: ping-render-cron

on:
  schedule:
    - cron: "*/5 * * * *"   # каждые 5 минут (время — UTC)
  workflow_dispatch: {}      # можно запустить вручную

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Wake & run due reminders
        run: |
          set -e
          curl -sS -X POST "${{ secrets.RENDER_CRON_URL }}" \
            -H "X-Cron-Token: ${{ secrets.CRON_TOKEN }}" \
            -H "Content-Length: 0" \
            -o /dev/stderr -w "HTTP %{http_code}\n"
