name: keepalive-and-cron

on:
  schedule:
    - cron: "*/5 * * * *"     # 00,05,10,15...
    - cron: "1-59/5 * * * *"  # 01,06,11,16...
    - cron: "2-59/5 * * * *"  # 02,07,12,17...
    - cron: "3-59/5 * * * *"  # 03,08,13,18...
    - cron: "4-59/5 * * * *"  # 04,09,14,19...
  workflow_dispatch: {}

concurrency:
  group: keepalive
  cancel-in-progress: false

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Warm up (GET /) to wake the service
        run: |
          curl -fsS "${{ secrets.RENDER_ROOT_URL }}/" -o /dev/null

      - name: Process due reminders (POST /cron/due)
        run: |
          curl -fsS -X POST "${{ secrets.RENDER_CRON_URL }}" \
            -H "X-Cron-Token: ${{ secrets.CRON_TOKEN }}" \
            -H "Content-Length: 0" -o /dev/null
